/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lucytest;

import com.nhncorp.lucy.security.xss.XssSaxFilter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        XssSaxFilter filter = XssSaxFilter.getInstance("lucy-xss-sax.xml", false);
        String dirty = "<iframe src=\"https://www.youtube.com\" onerror=alert(1)></iframe>";
        String clean = filter.doFilter(dirty);
        System.out.println(clean);
    }
}
