name: List Languages

on:
  workflow_dispatch:

jobs:
  detect_language:
    runs-on: ubuntu-latest

    steps:
      - name: Detect repository language and set config file
        id: set_config
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: languages } = await github.rest.repos.listLanguages({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Semgrep 규칙과 GitHub 언어 매핑
            const languageMap = {
              'Java': 'java',
              'Python': 'python',
              'JavaScript': 'javascript',
              'TypeScript': 'typescript',
              'Go': 'go',
              'PHP': 'php',
              'C++': 'cpp',
              'C#': 'csharp',
              'Ruby': 'ruby',
            };
            
            let mainLanguage = null;
            let maxBytes = 0;
            for (const lang in languages) {
              if (languages[lang] > maxBytes) {
                maxBytes = languages[lang];
                mainLanguage = lang;
              }
            }

            if (mainLanguage) {
              const semgrepLanguage = languageMap[mainLanguage];
              if (semgrepLanguage) {
                console.log(`주요 언어 '${mainLanguage}' 감지`);
              }
            } else {
              console.log('리포지토리의 언어를 감지하지 못했습니다.')
            }
