# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow file requires a free account on Semgrep.dev to
# manage rules, file ignores, notifications, and more.
#
# See https://semgrep.dev/docs

name: Semgrep

on:
  pull_request:
    types: ["opened", "reopened"]
    branches: ["master"]

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    
    container:
      image: returntocorp/semgrep
      
    steps:
      # Checkout project source
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_RULES: p/default
          SEMGREP_BASELINE_REF: master
